<?php require 'application/layouts/header.phtml'; ?>

<div class="container">
    <h2>Редактировать как администратор</h2>

    <form action="/index.php?controller=admin&action=save" method="post">
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Текст задачи</label>
            <textarea name="text_task" class="form-control" id="exampleFormControlTextarea1" rows="3"><?php echo $row['task_text']; ?></textarea>
        </div>
        <div class="form-group form-check">
            <input type="checkbox" name="task_done" value="done" class="form-check-input" id="exampleCheck1" <?php echo $status_checked; ?>>
            <label class="form-check-label" for="exampleCheck1">Выполнено</label>
        </div>
        <input type="hidden" name="task_id" value="<?php echo $row['id']; ?>">

        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>

<?php require 'application/layouts/footer.phtml'; ?>
