<?php require 'application/layouts/header.phtml'; ?>
<div class="container">
    <h2>Авторизация</h2>

    <form action="/index.php?controller=authorization&action=auth" method="post">
      <div class="form-group">
        <label for="exampleInputName">Имя</label>
        <input type="text" name="user_name" class="form-control col-md-4" id="exampleInputName" required>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Пароль</label>
        <input type="password" name="user_password" class="form-control col-md-4" id="exampleInputPassword1" required>
      </div>
      <button type="submit" class="btn btn-primary">Войти</button>
    </form>
</div>

<?php require 'application/layouts/footer.phtml'; ?>
